- file:      尾形聡彦.jpg
  source:    https://arctimes.com/from-founder/
  copyright: null

- file:      望月衣塑子.jpg
  source:    https://www.tokyo-np.co.jp/tags_reporter/m1/motizk_i
  copyright: null

- file:      本間龍.jpg
  source:    https://www.amazon.co.jp/%E6%9C%AC%E9%96%93-%E9%BE%8D/e/B004LW6PX4
  copyright: null

- file:      佐藤章.jpg
  source:    https://twitter.com/bSM2TC2coIKWrlM
  copyright: null

- file:      松谷創一郎.jpg
  source:    https://life.www.tbsradio.jp/2014/01/02/index.html
  copyright: 会田邦秋

- file:      鈴木エイト.jpg
  source:    https://jisin.jp/domestic/2250493/
  copyright: 時事通信

- file:      藤森祥平.jpg
  source:    https://www.huffingtonpost.jp/entry/story_jp_651f8ae3e4b076f0bd0ed59e
  copyright: TBS

- file:      駒井千佳子.jpg
  source:    https://www.nikkan-gendai.com/articles/view/geino/277753
  copyright: 日刊ゲンダイ
